// Code generated by mockery v2.53.6. DO NOT EDIT.

package stockmock

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	models "supermarket/internal/models"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockRepository) Create(ctx context.Context, p *models.Stock) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Stock) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *models.Stock
func (_e *MockRepository_Expecter) Create(ctx interface{}, p interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, p *models.Stock)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Stock))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Stock) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FirstOrCreateByProductID provides a mock function with given fields: ctx, productID
func (_m *MockRepository) FirstOrCreateByProductID(ctx context.Context, productID uuid.UUID) (*models.Stock, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for FirstOrCreateByProductID")
	}

	var r0 *models.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Stock, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Stock); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FirstOrCreateByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstOrCreateByProductID'
type MockRepository_FirstOrCreateByProductID_Call struct {
	*mock.Call
}

// FirstOrCreateByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockRepository_Expecter) FirstOrCreateByProductID(ctx interface{}, productID interface{}) *MockRepository_FirstOrCreateByProductID_Call {
	return &MockRepository_FirstOrCreateByProductID_Call{Call: _e.mock.On("FirstOrCreateByProductID", ctx, productID)}
}

func (_c *MockRepository_FirstOrCreateByProductID_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockRepository_FirstOrCreateByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_FirstOrCreateByProductID_Call) Return(_a0 *models.Stock, _a1 error) *MockRepository_FirstOrCreateByProductID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FirstOrCreateByProductID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Stock, error)) *MockRepository_FirstOrCreateByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockRepository) GetAll(ctx context.Context) ([]*models.Stock, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Stock, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Stock); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetAll(ctx interface{}) *MockRepository_GetAll_Call {
	return &MockRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetAll_Call) Return(_a0 []*models.Stock, _a1 error) *MockRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*models.Stock, error)) *MockRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Stock, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Stock, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Stock); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 *models.Stock, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Stock, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByParams provides a mock function with given fields: ctx, search, productID
func (_m *MockRepository) GetByParams(ctx context.Context, search string, productID *uuid.UUID) ([]models.Stock, error) {
	ret := _m.Called(ctx, search, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetByParams")
	}

	var r0 []models.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *uuid.UUID) ([]models.Stock, error)); ok {
		return rf(ctx, search, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *uuid.UUID) []models.Stock); ok {
		r0 = rf(ctx, search, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *uuid.UUID) error); ok {
		r1 = rf(ctx, search, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByParams'
type MockRepository_GetByParams_Call struct {
	*mock.Call
}

// GetByParams is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - productID *uuid.UUID
func (_e *MockRepository_Expecter) GetByParams(ctx interface{}, search interface{}, productID interface{}) *MockRepository_GetByParams_Call {
	return &MockRepository_GetByParams_Call{Call: _e.mock.On("GetByParams", ctx, search, productID)}
}

func (_c *MockRepository_GetByParams_Call) Run(run func(ctx context.Context, search string, productID *uuid.UUID)) *MockRepository_GetByParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetByParams_Call) Return(_a0 []models.Stock, _a1 error) *MockRepository_GetByParams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByParams_Call) RunAndReturn(run func(context.Context, string, *uuid.UUID) ([]models.Stock, error)) *MockRepository_GetByParams_Call {
	_c.Call.Return(run)
	return _c
}

// SetCountByProductID provides a mock function with given fields: ctx, productID, count
func (_m *MockRepository) SetCountByProductID(ctx context.Context, productID uuid.UUID, count decimal.Decimal) error {
	ret := _m.Called(ctx, productID, count)

	if len(ret) == 0 {
		panic("no return value specified for SetCountByProductID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r0 = rf(ctx, productID, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetCountByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCountByProductID'
type MockRepository_SetCountByProductID_Call struct {
	*mock.Call
}

// SetCountByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - count decimal.Decimal
func (_e *MockRepository_Expecter) SetCountByProductID(ctx interface{}, productID interface{}, count interface{}) *MockRepository_SetCountByProductID_Call {
	return &MockRepository_SetCountByProductID_Call{Call: _e.mock.On("SetCountByProductID", ctx, productID, count)}
}

func (_c *MockRepository_SetCountByProductID_Call) Run(run func(ctx context.Context, productID uuid.UUID, count decimal.Decimal)) *MockRepository_SetCountByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(decimal.Decimal))
	})
	return _c
}

func (_c *MockRepository_SetCountByProductID_Call) Return(_a0 error) *MockRepository_SetCountByProductID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetCountByProductID_Call) RunAndReturn(run func(context.Context, uuid.UUID, decimal.Decimal) error) *MockRepository_SetCountByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, t
func (_m *MockRepository) Update(ctx context.Context, t *models.Stock) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Stock) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - t *models.Stock
func (_e *MockRepository_Expecter) Update(ctx interface{}, t interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, t)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, t *models.Stock)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Stock))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Stock) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStockByCancellation provides a mock function with given fields: ctx, cancellationID, newQuantity
func (_m *MockRepository) UpdateStockByCancellation(ctx context.Context, cancellationID uuid.UUID, newQuantity decimal.Decimal) error {
	ret := _m.Called(ctx, cancellationID, newQuantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStockByCancellation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r0 = rf(ctx, cancellationID, newQuantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateStockByCancellation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStockByCancellation'
type MockRepository_UpdateStockByCancellation_Call struct {
	*mock.Call
}

// UpdateStockByCancellation is a helper method to define mock.On call
//   - ctx context.Context
//   - cancellationID uuid.UUID
//   - newQuantity decimal.Decimal
func (_e *MockRepository_Expecter) UpdateStockByCancellation(ctx interface{}, cancellationID interface{}, newQuantity interface{}) *MockRepository_UpdateStockByCancellation_Call {
	return &MockRepository_UpdateStockByCancellation_Call{Call: _e.mock.On("UpdateStockByCancellation", ctx, cancellationID, newQuantity)}
}

func (_c *MockRepository_UpdateStockByCancellation_Call) Run(run func(ctx context.Context, cancellationID uuid.UUID, newQuantity decimal.Decimal)) *MockRepository_UpdateStockByCancellation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(decimal.Decimal))
	})
	return _c
}

func (_c *MockRepository_UpdateStockByCancellation_Call) Return(_a0 error) *MockRepository_UpdateStockByCancellation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateStockByCancellation_Call) RunAndReturn(run func(context.Context, uuid.UUID, decimal.Decimal) error) *MockRepository_UpdateStockByCancellation_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStockByProductSale provides a mock function with given fields: ctx, productSaleID, newQuantity
func (_m *MockRepository) UpdateStockByProductSale(ctx context.Context, productSaleID uuid.UUID, newQuantity decimal.Decimal) error {
	ret := _m.Called(ctx, productSaleID, newQuantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStockByProductSale")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r0 = rf(ctx, productSaleID, newQuantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateStockByProductSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStockByProductSale'
type MockRepository_UpdateStockByProductSale_Call struct {
	*mock.Call
}

// UpdateStockByProductSale is a helper method to define mock.On call
//   - ctx context.Context
//   - productSaleID uuid.UUID
//   - newQuantity decimal.Decimal
func (_e *MockRepository_Expecter) UpdateStockByProductSale(ctx interface{}, productSaleID interface{}, newQuantity interface{}) *MockRepository_UpdateStockByProductSale_Call {
	return &MockRepository_UpdateStockByProductSale_Call{Call: _e.mock.On("UpdateStockByProductSale", ctx, productSaleID, newQuantity)}
}

func (_c *MockRepository_UpdateStockByProductSale_Call) Run(run func(ctx context.Context, productSaleID uuid.UUID, newQuantity decimal.Decimal)) *MockRepository_UpdateStockByProductSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(decimal.Decimal))
	})
	return _c
}

func (_c *MockRepository_UpdateStockByProductSale_Call) Return(_a0 error) *MockRepository_UpdateStockByProductSale_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateStockByProductSale_Call) RunAndReturn(run func(context.Context, uuid.UUID, decimal.Decimal) error) *MockRepository_UpdateStockByProductSale_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStockByProductSupply provides a mock function with given fields: ctx, productSupplyID, newQuantity
func (_m *MockRepository) UpdateStockByProductSupply(ctx context.Context, productSupplyID uuid.UUID, newQuantity decimal.Decimal) error {
	ret := _m.Called(ctx, productSupplyID, newQuantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStockByProductSupply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r0 = rf(ctx, productSupplyID, newQuantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateStockByProductSupply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStockByProductSupply'
type MockRepository_UpdateStockByProductSupply_Call struct {
	*mock.Call
}

// UpdateStockByProductSupply is a helper method to define mock.On call
//   - ctx context.Context
//   - productSupplyID uuid.UUID
//   - newQuantity decimal.Decimal
func (_e *MockRepository_Expecter) UpdateStockByProductSupply(ctx interface{}, productSupplyID interface{}, newQuantity interface{}) *MockRepository_UpdateStockByProductSupply_Call {
	return &MockRepository_UpdateStockByProductSupply_Call{Call: _e.mock.On("UpdateStockByProductSupply", ctx, productSupplyID, newQuantity)}
}

func (_c *MockRepository_UpdateStockByProductSupply_Call) Run(run func(ctx context.Context, productSupplyID uuid.UUID, newQuantity decimal.Decimal)) *MockRepository_UpdateStockByProductSupply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(decimal.Decimal))
	})
	return _c
}

func (_c *MockRepository_UpdateStockByProductSupply_Call) Return(_a0 error) *MockRepository_UpdateStockByProductSupply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateStockByProductSupply_Call) RunAndReturn(run func(context.Context, uuid.UUID, decimal.Decimal) error) *MockRepository_UpdateStockByProductSupply_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStockOnDeleteSale provides a mock function with given fields: ctx, saleID
func (_m *MockRepository) UpdateStockOnDeleteSale(ctx context.Context, saleID uuid.UUID) error {
	ret := _m.Called(ctx, saleID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStockOnDeleteSale")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, saleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateStockOnDeleteSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStockOnDeleteSale'
type MockRepository_UpdateStockOnDeleteSale_Call struct {
	*mock.Call
}

// UpdateStockOnDeleteSale is a helper method to define mock.On call
//   - ctx context.Context
//   - saleID uuid.UUID
func (_e *MockRepository_Expecter) UpdateStockOnDeleteSale(ctx interface{}, saleID interface{}) *MockRepository_UpdateStockOnDeleteSale_Call {
	return &MockRepository_UpdateStockOnDeleteSale_Call{Call: _e.mock.On("UpdateStockOnDeleteSale", ctx, saleID)}
}

func (_c *MockRepository_UpdateStockOnDeleteSale_Call) Run(run func(ctx context.Context, saleID uuid.UUID)) *MockRepository_UpdateStockOnDeleteSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_UpdateStockOnDeleteSale_Call) Return(_a0 error) *MockRepository_UpdateStockOnDeleteSale_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateStockOnDeleteSale_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRepository_UpdateStockOnDeleteSale_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
