// Code generated by mockery v2.53.6. DO NOT EDIT.

package transactionsnmock

import (
	context "context"
	transactions "supermarket/internal/repository/transactions"

	mock "github.com/stretchr/testify/mock"
)

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: ctx, fn
func (_m *MockUnitOfWork) Do(ctx context.Context, fn func(context.Context, transactions.Repositories) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, transactions.Repositories) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitOfWork_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockUnitOfWork_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context , transactions.Repositories) error
func (_e *MockUnitOfWork_Expecter) Do(ctx interface{}, fn interface{}) *MockUnitOfWork_Do_Call {
	return &MockUnitOfWork_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *MockUnitOfWork_Do_Call) Run(run func(ctx context.Context, fn func(context.Context, transactions.Repositories) error)) *MockUnitOfWork_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context, transactions.Repositories) error))
	})
	return _c
}

func (_c *MockUnitOfWork_Do_Call) Return(_a0 error) *MockUnitOfWork_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Do_Call) RunAndReturn(run func(context.Context, func(context.Context, transactions.Repositories) error) error) *MockUnitOfWork_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
