// Code generated by mockery v2.53.6. DO NOT EDIT.

package productsalemock

import (
	context "context"
	models "supermarket/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockRepository) Create(ctx context.Context, p *models.ProductSale) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ProductSale) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *models.ProductSale
func (_e *MockRepository_Expecter) Create(ctx interface{}, p interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, p *models.ProductSale)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.ProductSale))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *models.ProductSale) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBySale provides a mock function with given fields: ctx, saleID
func (_m *MockRepository) DeleteBySale(ctx context.Context, saleID uuid.UUID) error {
	ret := _m.Called(ctx, saleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBySale")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, saleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteBySale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBySale'
type MockRepository_DeleteBySale_Call struct {
	*mock.Call
}

// DeleteBySale is a helper method to define mock.On call
//   - ctx context.Context
//   - saleID uuid.UUID
func (_e *MockRepository_Expecter) DeleteBySale(ctx interface{}, saleID interface{}) *MockRepository_DeleteBySale_Call {
	return &MockRepository_DeleteBySale_Call{Call: _e.mock.On("DeleteBySale", ctx, saleID)}
}

func (_c *MockRepository_DeleteBySale_Call) Run(run func(ctx context.Context, saleID uuid.UUID)) *MockRepository_DeleteBySale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_DeleteBySale_Call) Return(_a0 error) *MockRepository_DeleteBySale_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteBySale_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRepository_DeleteBySale_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockRepository) GetAll(ctx context.Context) ([]*models.ProductSale, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.ProductSale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.ProductSale, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.ProductSale); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ProductSale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetAll(ctx interface{}) *MockRepository_GetAll_Call {
	return &MockRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetAll_Call) Return(_a0 []*models.ProductSale, _a1 error) *MockRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*models.ProductSale, error)) *MockRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.ProductSale, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.ProductSale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.ProductSale, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.ProductSale); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ProductSale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 *models.ProductSale, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.ProductSale, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySale provides a mock function with given fields: ctx, saleID
func (_m *MockRepository) GetBySale(ctx context.Context, saleID uuid.UUID) ([]models.ProductSale, error) {
	ret := _m.Called(ctx, saleID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySale")
	}

	var r0 []models.ProductSale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.ProductSale, error)); ok {
		return rf(ctx, saleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.ProductSale); ok {
		r0 = rf(ctx, saleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ProductSale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, saleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetBySale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySale'
type MockRepository_GetBySale_Call struct {
	*mock.Call
}

// GetBySale is a helper method to define mock.On call
//   - ctx context.Context
//   - saleID uuid.UUID
func (_e *MockRepository_Expecter) GetBySale(ctx interface{}, saleID interface{}) *MockRepository_GetBySale_Call {
	return &MockRepository_GetBySale_Call{Call: _e.mock.On("GetBySale", ctx, saleID)}
}

func (_c *MockRepository_GetBySale_Call) Run(run func(ctx context.Context, saleID uuid.UUID)) *MockRepository_GetBySale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetBySale_Call) Return(_a0 []models.ProductSale, _a1 error) *MockRepository_GetBySale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetBySale_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.ProductSale, error)) *MockRepository_GetBySale_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, t
func (_m *MockRepository) Update(ctx context.Context, t *models.ProductSale) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ProductSale) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - t *models.ProductSale
func (_e *MockRepository_Expecter) Update(ctx interface{}, t interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, t)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, t *models.ProductSale)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.ProductSale))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, *models.ProductSale) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
